######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 27 00:06:56 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += star.cpp
