######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 26 10:00:02 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += fact.cpp
